language: python

jobs:
  include:
    - name: "3.8-dev"
      dist: xenial
      python: 3.8-dev
    - name: "3.7.3"
      dist: xenial
      python: 3.7.3
    - name: "3.7.2"
      dist: xenial
      python: 3.7.2
    - name: "3.7.1"
      dist: xenial
      python: 3.7.1
    - name: "3.7.0"
      dist: xenial
      python: 3.7.0
    - name: "3.6.3"
      python: 3.6.3
    - name: "3.6.2"
      python: 3.6.2
    - name: "3.6.1"
      python: 3.6.1
    - name: "3.6.0"
      python: 3.6.0
    - name: "3.5.3"
      python: 3.5.3
    - name: "3.5.2"
      python: 3.5.2
    - name: "3.5.1"
      python: 3.5.1
    - name: "3.5.0"
      python: 3.5.0
    - name: "3.4"
      python: 3.4
    - name: "2.7"
      python: 2.7

install:
- pip install -r test-requirements.txt

script:
  - export PYTHONPATH=`python -c "import sys; print('python2' if sys.version.startswith('2') else 'src')"`;
    if [[ $TRAVIS_PYTHON_VERSION < '3.7' ]]; then py.test $PYTHONPATH; fi
  - if [[ $TRAVIS_PYTHON_VERSION < '3.5' ]]; then python setup.py install; fi
  - export PYTHONPATH=`python -c "import sys; print('typing_extensions/src_py2' if sys.version.startswith('2') else 'typing_extensions/src_py3')"`;
    py.test $PYTHONPATH;
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 --config=.flake8-tests src/test_typing.py python2/test_typing.py typing_extensions/src_py2/test_typing_extensions.py typing_extensions/src_py3/test_typing_extensions.py; fi
